services:
  odoo:
    image: odoo:17
    ports:
      - "8069:8069"
    command: odoo -c /etc/odoo/odoo.conf  -i chartly --stop-after-init --test-tags=/chartly --logfile=
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
    secrets:
      - openai_api_key
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - OPENAI_API_KEY_FILE=/run/secrets/openai_api_key
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  odoo-web-data:
  db-data:

secrets:
  openai_api_key:
    file: secrets/openai_api_key.txt