services:
  odoo:
    image: odoo:17
    ports:
      - "8069:8069"
    command: bash -c 'pip install -r /mnt/extra-addons/chartly/requirements.txt && odoo -c /etc/odoo/odoo.conf -u base,chartly --logfile= --without-demo=all'
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
    secrets:
      - openai_api_key
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  odoo-web-data:
  db-data:

secrets:
  openai_api_key:
    file: secrets/openai_api_key.txt
